references:
  builderbox: &builderbox
    docker:
      - image: circleci/ruby:2.4-node
      
  make_folder: &make_folder
    run: mkdir foo
    
  do_checkout: &do_checkout
      - checkout
      - run: git status
  run_on_master_tagged: &run_on_master_tagged
    filters:
      branches:
        only: /master/
      tags:
        ignore: /^v.*/

jobs:
  build:
    <<: *builderbox
    steps:
      - run: npm install   
  test:
    <<: *builderbox
    steps:
      - checkout
      - run: git status
      
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - build:
          <<: *run_on_master_tagged        
      - test
            


