version: 2

references:
  builderbox: &builderbox
    docker:
      - image: circleci/ruby:2.3-browsers
      
  make_folder: &make_folder
    - run: mkdir foo
    
  do_checkout: &do_checkout
      - checkout
      - run: git status
  allthethings: &allthethings
    steps:
      - checkout
      - run: git status
      <<: *make_folder

jobs:
  build:
    <<: *builderbox
    <<: *allthethings


