version: 2.1

orbs:
  terraform: ovotech/terraform@dev:name

workflows:
  test:
    jobs:
      - terraform/plan:
          path: test
          environment: prod
      - terraform/apply:
          path: test
          environment: prod
          requires:
            - terraform/plan
          filters:
            branches:
              only: master
