references:
  builderbox: &builderbox
    docker:
      - image: ubuntu/16.04:latest
#    parallelism: 4
    
  do_checkout: &do_checkout
      - checkout
      - run: git status

jobs:
  build:
    <<: *builderbox
    steps:
      - checkout
      - run: apt-get update
      - run: echo "making some changes"
      
  test:
    docker:
      - image: ubuntu/16.04:latest
    steps:
      - run: echo "hey-o!"
      - run: echo $testVar
  iOS:
    macos: 
      xcode: "9.0.0"
    steps:
      - run: echo "hello world"
      - run: openssl version -a
      
  build_two:
    docker:
    - image: ubuntu/16.04
      environment:
        PDFTK_PATH: /usr/bin/pdftk

    steps:
      - run: apt-get update
      - run: apt-get install pdftk -y
      - run: bundle exec rubocop

      
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - build
      - build_two
      - test:
          context: Testing
      - iOS
      

