references:
  builderbox: &builderbox
    docker:
      - image: circleci/ruby:2.3.1-jessie-node-browsers
      
  make_folder: &make_folder
    run: mkdir foo
    
  do_checkout: &do_checkout
      - checkout
      - run: git status

jobs:
  build:
    <<: *builderbox
    steps:
      - checkout
      - run: git status    
  test:
    <<: *builderbox
    steps:
      - checkout
      - run: git status
      
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
           - build
          filters:
            branches:
              ignore: /master/          
      - test:
          requires:
            - hold
          filters:
            branches:
              ignore: /master/              


