version: 2.0
jobs:
  build:
    docker:
    - image: circleci/node:9.10
    parallelism: 2
    working_directory: ~/build
    steps:
    - checkout
    - run:
        name: Installing modules
        command: yarn install
    - run:
        name: Running unit tests
        command: |
          mkdir -p reports/jest
          yarn test
        environment:
          JEST_JUNIT_OUTPUT: reports/jest/results.xml
    - store_test_results:
        path: reports
    - store_artifacts:
        path: reports
workflows:
  version: 2
  commit:
    jobs:
    - build
