references:
  builderbox: &builderbox
    docker:
      - image: circleci/php:7.2.10-cli-stretch-node-browsers-legacy
#    parallelism: 4
    
  do_checkout: &do_checkout
      - checkout
      - run: git status

jobs:
  build:
    <<: *builderbox
    steps:
      - run: npm install
  test:
    <<: *builderbox
    steps:
      - checkout
      - run: git status
      - run: echo $Saras_Test
      - run: cd ios && bundle exec fastlane $FASTLANE_LANE
  iOS:
    macos: 
      xcode: "10.0.0"
    steps:
      - run: echo "hello world"

      
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - build      
      - test:
          context: Testing
      - iOS
  prod-scheduled-workflow:
    triggers:
      - schedule:
          cron: "5 * * * *"
          filters:
              branches:
                only: 
                  - /master/
    jobs:
      - build
