version: 2
jobs:
  git_check:
    docker:
      - image: circleci/ruby:2.3-slim
    steps:
      - checkout
      - run: git status
  list:
    docker:
      - image: circleci/ruby:2.3-slim
    steps:
      - checkout
      - run: ls

workflows:
  version: 2
  build_and_test:
    jobs:
      - git_check:
          filters:
            branches:
              only:
                - approval
      - list:
          filters:
            branches:
              only: approval
