references:
  builderbox: &builderbox
    docker:
      - image: circleci/php:7.2.3-fpm-node-browsers
      
  make_folder: &make_folder
    run: mkdir foo
    
  do_checkout: &do_checkout
      - checkout
      - run: git status
  run_on_master_tagged: &run_on_master_tagged
    filters:
      branches:
        only: /master/
      tags:
        ignore: /^v.*/

jobs:
  build:
    <<: *builderbox
    steps:
      - run: npm install   
  test:
    <<: *builderbox
    steps:
      - checkout
      - run: git status
      - run: echo $Saras_Test
      
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - build:
          <<: *run_on_master_tagged        
      - test:
          context: Testing
      
#just making a commit

notify:
  webhooks:
    - url: http://requestbin.fullcontact.com/ud6l8jud
            


