references:
  builderbox: &builderbox
    docker:
      - image: circleci/php:7.2.10-cli-stretch-node-browsers-legacy
#    parallelism: 4
    
  do_checkout: &do_checkout
      - checkout
      - run: git status

jobs:
  build:
    <<: *builderbox
    steps:
      - run: npm install
  test:
    <<: *builderbox
    steps:
      - checkout
      - run: git status
      - run:
          name: Make a folder
          command: mkdir testfolder
      - run:
          name: mess up space
          command: mkdir anotherfolder
      - run: echo $Saras_Test
      - run: cd ios && bundle exec fastlane $FASTLANE_LANE
  iOS:
    macos: 
      xcode: "10.0.0"
    steps:
      - run: echo "hello world"
      
  build_two:
    docker:
    - image: quay.io/aptible/ruby:2.2
      environment:
        PDFTK_PATH: /usr/bin/pdftk

    steps:
      - run: apt-get update
      - run: apt-get install pdftk
      - run: bundle exec rubocop

      
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - build
      - build_two
      - test:
          context: Testing
      - iOS

