version: 2.1

orbs:
  terraform: ovotech/terraform@dev:name

workflows:
  test:
    jobs:
      - terraform/plan
      - terraform/apply:
          requires:
            - terraform/plan
          filters:
            branches:
              only: master
