references:
  builderbox: &builderbox
    docker:
      - image: node:10.15.0
#    parallelism: 4
    
  do_checkout: &do_checkout
      - checkout
      - run: git status

jobs:
  build:
    <<: *builderbox
    environment:
      BRANCH: test-encoding.3
    steps:
      - checkout
      - run: curl --data-urlencode "BRANCH"
      - run:
          name: Test timeout
          # Default timeout is 6m. Copy phase of docker build is currently taking longer than that
          command: sleep 7m
          NoOutputTimeout: 15
  test:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.12.1-ce
      - run:
          command: |
            docker run php:latest
            docker --version
      - run: git status
      - run: yarn install --silent
      - run:
          name: Make a folder
          command: mkdir testfolder
      - run:
          name: mess up space
          command: mkdir anotherfolder
      - run: echo $Saras_Test
      - run: cd ios && bundle exec fastlane $FASTLANE_LANE
  iOS:
    macos: 
      xcode: "9.0.0"
    steps:
      - run: echo "hello world"
      - run: openssl version -a
      
  build_two:
    docker:
    - image: circleci/php@sha256:50d128524a5930b3cc0ccec8906883d7c7feffc8611bbfdffb762f0136c06357
      environment:
        PDFTK_PATH: /usr/bin/pdftk

    steps:
      - run: apt-get update
      - run: apt-get install pdftk -y
      - run: bundle exec rubocop

      
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - build
      - build_two
      - test:
          context: Testing
      - iOS
      

