version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-ndk-r17b
    steps:
      - run: echo "$CIRCLECI"
      - run: echo $CIRCLECI
      - run: echo "Circle Value\: $CIRCLECI"
      - run: echo "Circle Value\: " $CIRCLECI
      
      
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - build
      

