version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-ndk-r17b
    steps:
      - checkout
      - run: cd .circleci
      - run: sudo ./script.sh
      
      
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - build
      

